library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Tang Nano 20K DOCK joystick interface for MSXnano/YM2149.
--
-- DOCK:
--   JS_Clk    = PHI2
--   JS_Load_N = parallel load
--   JS_Data   = serial data
--
-- YM2149:
--   I_IOA = PSG R#14 input
--   O_IOB = PSG R#15 output
--
-- R#15 bit 6:
--   0 = joystick 1
--   1 = joystick 2
--
-- R#14:
--   bit 0 = Up
--   bit 1 = Down
--   bit 2 = Left
--   bit 3 = Right
--   bit 4 = Trigger A
--   bit 5 = Trigger B
--   bit 6 = JIS/KANA (not provided by DOCK)
--   bit 7 = CASRD     (not provided by DOCK)

entity msxnano_dock_joystick is
    port (
        clock       : in  std_logic;
        reset_n     : in  std_logic;

        phi2        : in  std_logic;
        js_data     : in  std_logic;
        js_load_n   : out std_logic;

        -- YM2149 R#15 output
        psg_r15     : in  std_logic_vector(7 downto 0);

        -- YM2149 R#14 input
        psg_ioa     : out std_logic_vector(7 downto 0)
    );
end entity;

architecture rtl of msxnano_dock_joystick is

    signal last_phi2 : std_logic := '0';

    signal sr_counter : unsigned(4 downto 0) :=
        (others => '0');

    -- Same 17-bit mirror used by BeebFPGA.
    signal sr_mirror : std_logic_vector(16 downto 0) :=
        (others => '0');

    signal joystick1 : std_logic_vector(4 downto 0) :=
        (others => '0');

    signal joystick2 : std_logic_vector(4 downto 0) :=
        (others => '0');

    signal fire1_n : std_logic := '1';
    signal fire2_n : std_logic := '1';

begin

    ------------------------------------------------------------------------
    -- DOCK 74LV165 interface
    --
    -- This follows the BeebFPGA shift_register.vhd timing:
    --
    --   PHI2 falling edge:
    --       update JS_LOAD_N
    --       optionally decode current frame
    --       shift JS_DATA into sr_mirror
    ------------------------------------------------------------------------

    process(clock)
    begin
        if rising_edge(clock) then

            if reset_n = '0' then

                last_phi2  <= '0';
                sr_counter <= (others => '0');
                sr_mirror  <= (others => '0');

                joystick1 <= (others => '0');
                joystick2 <= (others => '0');

                fire1_n <= '1';
                fire2_n <= '1';

                js_load_n <= '0';

            else

                if phi2 = '0' and last_phi2 = '1' then

                    if sr_counter(4) = '1' then

                        js_load_n <= '0';
                        sr_counter <= (others => '0');

                    else

                        js_load_n <= '1';
                        sr_counter <= sr_counter + 1;

                    end if;


                    ----------------------------------------------------------------
                    -- Decode one complete frame.
                    --
                    -- Version 1.00
                    ----------------------------------------------------------------

                    if sr_counter = "00000" then

                        if sr_mirror(0) = '0' then

                            joystick1 <= sr_mirror(13 downto 9);
                            joystick2 <= sr_mirror(5 downto 1);

                            fire1_n <= sr_mirror(13);
                            fire2_n <= sr_mirror(5);

                        else

                            ----------------------------------------------------------------
                            -- Version 1.01 and later
                            ----------------------------------------------------------------

                            joystick1 <= sr_mirror(5 downto 1);
                            joystick2 <= sr_mirror(5 downto 1);

                            fire1_n <= sr_mirror(9);
                            fire2_n <= sr_mirror(10);

                        end if;

                    end if;


                    ----------------------------------------------------------------
                    -- Shift serial data.
                    --
                    -- This direction is intentionally identical to the
                    -- BeebFPGA implementation.
                    ----------------------------------------------------------------

                    sr_mirror <=
                        sr_mirror(15 downto 0) & js_data;

                end if;

                last_phi2 <= phi2;

            end if;
        end if;
    end process;


    ------------------------------------------------------------------------
    -- Convert DOCK joystick data to YM2149 R#14.
    --
    -- R#15 bit 6 is generated by YM2149 itself, so this module only uses
    -- it as the joystick selector.
    ------------------------------------------------------------------------

    process(joystick1,
            joystick2,
            fire1_n,
            fire2_n,
            psg_r15)

        variable joy : std_logic_vector(7 downto 0);

    begin

        -- All inputs inactive.
        joy := (others => '1');


        if psg_r15(6) = '0' then

            -- Joystick 1
            joy(3 downto 0) := joystick1(3 downto 0);
            joy(4) := fire1_n;

        else

            -- Joystick 2
            joy(3 downto 0) := joystick2(3 downto 0);
            joy(4) := fire2_n;

        end if;


        -- DOCK does not provide these MSX PSG inputs.
        -- Active-low inputs => inactive = 1.
        joy(5) := '1';
        joy(6) := '1';
        joy(7) := '1';

        psg_ioa <= joy;

    end process;

end architecture;